"""empty message

Revision ID: ec62426c1f58
Revises: 
Create Date: 2023-10-01 05:58:46.816397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec62426c1f58'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("('group_members',)")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table("('group_members',)",
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"(\'\'group_members\'\',)_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name="('group_members',)_group_id_fkey", ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name="('group_members',)_user_id_fkey", ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name="('group_members',)_pkey")
    )
    # ### end Alembic commands ###
